# Custom Language File for Launcher Customizer

[ejs.app]
title = "Exe And Chill Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Xenows76/exeandchill"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/dFZDtjrpwE"

[ejs.settings]
sourceGithubLink = "https://github.com/Xenows76/exeandchill"
supportLink = "https://github.com/Xenows76/exeandchillissues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR EXE AND CHILL"
welcomeDescription = "Votre objectif sur le serveur est de capturer le plus de pokémons ainsi que construire votre base. Amusez vous bien !"
welcomeDescCTA = "Tu es à quelques cliques de rejoindre Exe And Chill."
